server:
  port: 8010

spring:
  application:
    name: music-capsule-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:musicdreamer}?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true